apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-info-rapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-info-rapp
  template:
    metadata:
      labels:
        app: device-info-rapp
    spec:
      containers:
      - name: device-info-rapp-container
        image: hsukevin121/device-info-rapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: device-info-rapp-service
spec:
  selector:
    app: device-info-rapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
