apiVersion: apps/v1
kind: Deployment
metadata:
  name: devicelist-rapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devicelist-rapp
  template:
    metadata:
      labels:
        app: devicelist-rapp
    spec:
      containers:
      - name: devicelist-rapp-container
        image: hsukevin121/devicelist-rapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devicelist-rapp-service
spec:
  selector:
    app: devicelist-rapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
